# Generated by Django 5.2.4 on 2025-07-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_video_category_video_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='time',
        ),
    ]
